export const WORD_DB = {
  action: {
    color: "#FF6B6B",
    label: "动作",
    items: [
      { t: "Running", e: "🏃", p: "/ˈrʌnɪŋ/", zh: "跑步", zhPron: "pao bu" },
      { t: "Swimming", e: "🏊", p: "/ˈswɪmɪŋ/", zh: "游泳", zhPron: "you yong" },
      { t: "Climbing", e: "🧗", p: "/ˈklaɪmɪŋ/", zh: "攀爬", zhPron: "pan pa" },
      { t: "Flying", e: "✈️", p: "/ˈflaɪɪŋ/", zh: "飞行", zhPron: "fei xing" },
      { t: "Cooking", e: "👨‍🍳", p: "/ˈkʊkɪŋ/", zh: "烹饪", zhPron: "peng ren" },
      { t: "Painting", e: "🎨", p: "/ˈpeɪntɪŋ/", zh: "绘画", zhPron: "hui hua" },
      { t: "Building", e: "🏗️", p: "/ˈbɪldɪŋ/", zh: "建造", zhPron: "jian zao" },
      { t: "Learning", e: "📚", p: "/ˈlɜːrnɪŋ/", zh: "学习", zhPron: "xue xi" },
      { t: "Teaching", e: "👩‍🏫", p: "/ˈtiːtʃɪŋ/", zh: "教学", zhPron: "jiao xue" },
      { t: "Exploring", e: "🔍", p: "/ɪkˈsplɔːrɪŋ/", zh: "探索", zhPron: "tan suo" },
    ],
  },
  nature: {
    color: "#6BCB77",
    label: "自然",
    items: [
      { t: "Mountain", e: "⛰️", p: "/ˈmaʊntən/", zh: "高山", zhPron: "gao shan" },
      { t: "Ocean", e: "🌊", p: "/ˈəʊʃən/", zh: "海洋", zhPron: "hai yang" },
      { t: "Forest", e: "🌲", p: "/ˈfɔːrɪst/", zh: "森林", zhPron: "sen lin" },
      { t: "River", e: "🌊", p: "/ˈrɪvər/", zh: "河流", zhPron: "he liu" },
      { t: "Island", e: "🏝️", p: "/ˈaɪlənd/", zh: "岛屿", zhPron: "dao yu" },
      { t: "Valley", e: "🏔️", p: "/ˈvæli/", zh: "山谷", zhPron: "shan gu" },
      { t: "Desert", e: "🏜️", p: "/ˈdezərt/", zh: "沙漠", zhPron: "sha mo" },
      { t: "Beach", e: "🏖️", p: "/biːtʃ/", zh: "海滩", zhPron: "hai tan" },
      { t: "Volcano", e: "🌋", p: "/vɑːlˈkeɪnəʊ/", zh: "火山", zhPron: "huo shan" },
      { t: "Waterfall", e: "💧", p: "/ˈwɔːtərfɔːl/", zh: "瀑布", zhPron: "pu bu" },
    ],
  },
  animal: {
    color: "#FFE0B2",
    label: "动物",
    items: [
      { t: "Elephant", e: "🐘", p: "/ˈelɪfənt/", zh: "大象", zhPron: "da xiang" },
      { t: "Giraffe", e: "🦒", p: "/dʒɪˈræf/", zh: "长颈鹿", zhPron: "chang jing lu" },
      { t: "Dolphin", e: "🐬", p: "/ˈdɑːlfɪn/", zh: "海豚", zhPron: "hai tun" },
      { t: "Penguin", e: "🐧", p: "/ˈpeŋɡwɪn/", zh: "企鹅", zhPron: "qi e" },
      { t: "Kangaroo", e: "🦘", p: "/ˌkæŋɡəˈruː/", zh: "袋鼠", zhPron: "dai shu" },
      { t: "Butterfly", e: "🦋", p: "/ˈbʌtərflaɪ/", zh: "蝴蝶", zhPron: "hu die" },
      { t: "Turtle", e: "🐢", p: "/ˈtɜːrtəl/", zh: "乌龟", zhPron: "wu gui" },
      { t: "Octopus", e: "🐙", p: "/ˈɑːktəpəs/", zh: "章鱼", zhPron: "zhang yu" },
      { t: "Hippo", e: "🦛", p: "/ˈhɪpəʊ/", zh: "河马", zhPron: "he ma" },
      { t: "Crocodile", e: "🐊", p: "/ˈkrɑːkədaɪl/", zh: "鳄鱼", zhPron: "e yu" },
    ],
  },
  science: {
    color: "#4D96FF",
    label: "科学",
    items: [
      { t: "Planet", e: "🪐", p: "/ˈplænɪt/", zh: "行星", zhPron: "xing xing" },
      { t: "Rocket", e: "🚀", p: "/ˈrɑːkɪt/", zh: "火箭", zhPron: "huo jian" },
      { t: "Telescope", e: "🔭", p: "/ˈtelɪskəʊp/", zh: "望远镜", zhPron: "wang yuan jing" },
      { t: "Microscope", e: "🔬", p: "/ˈmaɪkrəskəʊp/", zh: "显微镜", zhPron: "xian wei jing" },
      { t: "Magnet", e: "🧲", p: "/ˈmæɡnɪt/", zh: "磁铁", zhPron: "ci tie" },
      { t: "Battery", e: "🔋", p: "/ˈbætəri/", zh: "电池", zhPron: "dian chi" },
      { t: "Computer", e: "💻", p: "/kəmˈpjuːtər/", zh: "电脑", zhPron: "dian nao" },
      { t: "Robot", e: "🤖", p: "/ˈrəʊbɑːt/", zh: "机器人", zhPron: "ji qi ren" },
      { t: "Satellite", e: "🛰️", p: "/ˈsætəlaɪt/", zh: "卫星", zhPron: "wei xing" },
      { t: "Astronaut", e: "👨‍🚀", p: "/ˈæstrənɔːt/", zh: "宇航员", zhPron: "yu hang yuan" },
    ],
  },
  emotion: {
    color: "#9B59B6",
    label: "情绪",
    items: [
      { t: "Happy", e: "😊", p: "/ˈhæpi/", zh: "开心", zhPron: "kai xin" },
      { t: "Excited", e: "🤩", p: "/ɪkˈsaɪtɪd/", zh: "兴奋", zhPron: "xing fen" },
      { t: "Surprised", e: "😲", p: "/sərˈpraɪzd/", zh: "惊讶", zhPron: "jing ya" },
      { t: "Proud", e: "😎", p: "/praʊd/", zh: "骄傲", zhPron: "jiao ao" },
      { t: "Curious", e: "🤔", p: "/ˈkjʊriəs/", zh: "好奇", zhPron: "hao qi" },
      { t: "Brave", e: "🦸", p: "/breɪv/", zh: "勇敢", zhPron: "yong gan" },
      { t: "Calm", e: "😌", p: "/kɑːm/", zh: "平静", zhPron: "ping jing" },
      { t: "Grateful", e: "🙏", p: "/ˈɡreɪtfəl/", zh: "感激", zhPron: "gan ji" },
      { t: "Confident", e: "💪", p: "/ˈkɑːnfɪdənt/", zh: "自信", zhPron: "zi xin" },
      { t: "Peaceful", e: "🕊️", p: "/ˈpiːsfəl/", zh: "宁静", zhPron: "ning jing" },
    ],
  },
  building: {
    color: "#FF9F43",
    label: "建筑",
    items: [
      { t: "Hospital", e: "🏥", p: "/ˈhɑːspɪtəl/", zh: "医院", zhPron: "yi yuan" },
      { t: "Library", e: "📚", p: "/ˈlaɪbreri/", zh: "图书馆", zhPron: "tu shu guan" },
      { t: "Museum", e: "🏛️", p: "/mjuːˈziːəm/", zh: "博物馆", zhPron: "bo wu guan" },
      { t: "Theater", e: "🎭", p: "/ˈθiːətər/", zh: "剧院", zhPron: "ju yuan" },
      { t: "Stadium", e: "🏟️", p: "/ˈsteɪdiəm/", zh: "体育场", zhPron: "ti yu chang" },
      { t: "Airport", e: "✈️", p: "/ˈerpɔːrt/", zh: "机场", zhPron: "ji chang" },
      { t: "Station", e: "🚉", p: "/ˈsteɪʃən/", zh: "车站", zhPron: "che zhan" },
      { t: "Bridge", e: "🌉", p: "/brɪdʒ/", zh: "桥梁", zhPron: "qiao liang" },
      { t: "Tower", e: "🗼", p: "/ˈtaʊər/", zh: "高塔", zhPron: "gao ta" },
      { t: "Castle", e: "🏰", p: "/ˈkæsəl/", zh: "城堡", zhPron: "cheng bao" },
    ],
  },
  food: {
    color: "#FF6B9D",
    label: "食物",
    items: [
      { t: "Sandwich", e: "🥪", p: "/ˈsænwɪtʃ/", zh: "三明治", zhPron: "san ming zhi" },
      { t: "Hamburger", e: "🍔", p: "/ˈhæmbɜːrɡər/", zh: "汉堡", zhPron: "han bao" },
      { t: "Spaghetti", e: "🍝", p: "/spəˈɡeti/", zh: "意大利面", zhPron: "yi da li mian" },
      { t: "Chocolate", e: "🍫", p: "/ˈtʃɑːklət/", zh: "巧克力", zhPron: "qiao ke li" },
      { t: "Strawberry", e: "🍓", p: "/ˈstrɔːberi/", zh: "草莓", zhPron: "cao mei" },
      { t: "Watermelon", e: "🍉", p: "/ˈwɔːtərmelən/", zh: "西瓜", zhPron: "xi gua" },
      { t: "Pineapple", e: "🍍", p: "/ˈpaɪnæpəl/", zh: "菠萝", zhPron: "bo luo" },
      { t: "Vegetable", e: "🥕", p: "/ˈvedʒtəbəl/", zh: "蔬菜", zhPron: "shu cai" },
      { t: "Breakfast", e: "🍳", p: "/ˈbrekfəst/", zh: "早餐", zhPron: "zao can" },
      { t: "Dinner", e: "🍽️", p: "/ˈdɪnər/", zh: "晚餐", zhPron: "wan can" },
    ],
  },
  sport: {
    color: "#00D2D3",
    label: "运动",
    items: [
      { t: "Basketball", e: "🏀", p: "/ˈbæskɪtbɔːl/", zh: "篮球", zhPron: "lan qiu" },
      { t: "Football", e: "⚽", p: "/ˈfʊtbɔːl/", zh: "足球", zhPron: "zu qiu" },
      { t: "Tennis", e: "🎾", p: "/ˈtenɪs/", zh: "网球", zhPron: "wang qiu" },
      { t: "Swimming", e: "🏊", p: "/ˈswɪmɪŋ/", zh: "游泳", zhPron: "you yong" },
      { t: "Cycling", e: "🚴", p: "/ˈsaɪklɪŋ/", zh: "骑行", zhPron: "qi xing" },
      { t: "Skating", e: "⛸️", p: "/ˈskeɪtɪŋ/", zh: "滑冰", zhPron: "hua bing" },
      { t: "Skiing", e: "⛷️", p: "/ˈskiːɪŋ/", zh: "滑雪", zhPron: "hua xue" },
      { t: "Surfing", e: "🏄", p: "/ˈsɜːrfɪŋ/", zh: "冲浪", zhPron: "chong lang" },
      { t: "Climbing", e: "🧗", p: "/ˈklaɪmɪŋ/", zh: "攀岩", zhPron: "pan yan" },
      { t: "Diving", e: "🤿", p: "/ˈdaɪvɪŋ/", zh: "跳水", zhPron: "tiao shui" },
    ],
  },
};
