export const WORD_DB = {
  action: {
    color: "#FF6B6B",
    label: "Action",
    items: [
      { t: "Running", e: "🏃", p: "/ˈrʌnɪŋ/" },
      { t: "Swimming", e: "🏊", p: "/ˈswɪmɪŋ/" },
      { t: "Climbing", e: "🧗", p: "/ˈklaɪmɪŋ/" },
      { t: "Flying", e: "✈️", p: "/ˈflaɪɪŋ/" },
      { t: "Cooking", e: "👨‍🍳", p: "/ˈkʊkɪŋ/" },
      { t: "Painting", e: "🎨", p: "/ˈpeɪntɪŋ/" },
      { t: "Building", e: "🏗️", p: "/ˈbɪldɪŋ/" },
      { t: "Learning", e: "📚", p: "/ˈlɜːrnɪŋ/" },
      { t: "Teaching", e: "👩‍🏫", p: "/ˈtiːtʃɪŋ/" },
      { t: "Exploring", e: "🔍", p: "/ɪkˈsplɔːrɪŋ/" },
    ],
  },
  nature: {
    color: "#6BCB77",
    label: "Nature",
    items: [
      { t: "Mountain", e: "⛰️", p: "/ˈmaʊntən/" },
      { t: "Ocean", e: "🌊", p: "/ˈəʊʃən/" },
      { t: "Forest", e: "🌲", p: "/ˈfɔːrɪst/" },
      { t: "River", e: "🌊", p: "/ˈrɪvər/" },
      { t: "Island", e: "🏝️", p: "/ˈaɪlənd/" },
      { t: "Valley", e: "🏔️", p: "/ˈvæli/" },
      { t: "Desert", e: "🏜️", p: "/ˈdezərt/" },
      { t: "Beach", e: "🏖️", p: "/biːtʃ/" },
      { t: "Volcano", e: "🌋", p: "/vɑːlˈkeɪnəʊ/" },
      { t: "Waterfall", e: "💧", p: "/ˈwɔːtərfɔːl/" },
    ],
  },
  animal: {
    color: "#FFE0B2",
    label: "Animal",
    items: [
      { t: "Elephant", e: "🐘", p: "/ˈelɪfənt/" },
      { t: "Giraffe", e: "🦒", p: "/dʒɪˈræf/" },
      { t: "Dolphin", e: "🐬", p: "/ˈdɑːlfɪn/" },
      { t: "Penguin", e: "🐧", p: "/ˈpeŋɡwɪn/" },
      { t: "Kangaroo", e: "🦘", p: "/ˌkæŋɡəˈruː/" },
      { t: "Butterfly", e: "🦋", p: "/ˈbʌtərflaɪ/" },
      { t: "Turtle", e: "🐢", p: "/ˈtɜːrtəl/" },
      { t: "Octopus", e: "🐙", p: "/ˈɑːktəpəs/" },
      { t: "Hippo", e: "🦛", p: "/ˈhɪpəʊ/" },
      { t: "Crocodile", e: "🐊", p: "/ˈkrɑːkədaɪl/" },
    ],
  },
  science: {
    color: "#4D96FF",
    label: "Science",
    items: [
      { t: "Planet", e: "🪐", p: "/ˈplænɪt/" },
      { t: "Rocket", e: "🚀", p: "/ˈrɑːkɪt/" },
      { t: "Telescope", e: "🔭", p: "/ˈtelɪskəʊp/" },
      { t: "Microscope", e: "🔬", p: "/ˈmaɪkrəskəʊp/" },
      { t: "Magnet", e: "🧲", p: "/ˈmæɡnɪt/" },
      { t: "Battery", e: "🔋", p: "/ˈbætəri/" },
      { t: "Computer", e: "💻", p: "/kəmˈpjuːtər/" },
      { t: "Robot", e: "🤖", p: "/ˈrəʊbɑːt/" },
      { t: "Satellite", e: "🛰️", p: "/ˈsætəlaɪt/" },
      { t: "Astronaut", e: "👨‍🚀", p: "/ˈæstrənɔːt/" },
    ],
  },
  emotion: {
    color: "#9B59B6",
    label: "Emotion",
    items: [
      { t: "Happy", e: "😊", p: "/ˈhæpi/" },
      { t: "Excited", e: "🤩", p: "/ɪkˈsaɪtɪd/" },
      { t: "Surprised", e: "😲", p: "/sərˈpraɪzd/" },
      { t: "Proud", e: "😎", p: "/praʊd/" },
      { t: "Curious", e: "🤔", p: "/ˈkjʊriəs/" },
      { t: "Brave", e: "🦸", p: "/breɪv/" },
      { t: "Calm", e: "😌", p: "/kɑːm/" },
      { t: "Grateful", e: "🙏", p: "/ˈɡreɪtfəl/" },
      { t: "Confident", e: "💪", p: "/ˈkɑːnfɪdənt/" },
      { t: "Peaceful", e: "🕊️", p: "/ˈpiːsfəl/" },
    ],
  },
  building: {
    color: "#FF9F43",
    label: "Building",
    items: [
      { t: "Hospital", e: "🏥", p: "/ˈhɑːspɪtəl/" },
      { t: "Library", e: "📚", p: "/ˈlaɪbreri/" },
      { t: "Museum", e: "🏛️", p: "/mjuːˈziːəm/" },
      { t: "Theater", e: "🎭", p: "/ˈθiːətər/" },
      { t: "Stadium", e: "🏟️", p: "/ˈsteɪdiəm/" },
      { t: "Airport", e: "✈️", p: "/ˈerpɔːrt/" },
      { t: "Station", e: "🚉", p: "/ˈsteɪʃən/" },
      { t: "Bridge", e: "🌉", p: "/brɪdʒ/" },
      { t: "Tower", e: "🗼", p: "/ˈtaʊər/" },
      { t: "Castle", e: "🏰", p: "/ˈkæsəl/" },
    ],
  },
  food: {
    color: "#FF6B9D",
    label: "Food",
    items: [
      { t: "Sandwich", e: "🥪", p: "/ˈsænwɪtʃ/" },
      { t: "Hamburger", e: "🍔", p: "/ˈhæmbɜːrɡər/" },
      { t: "Spaghetti", e: "🍝", p: "/spəˈɡeti/" },
      { t: "Chocolate", e: "🍫", p: "/ˈtʃɑːklət/" },
      { t: "Strawberry", e: "🍓", p: "/ˈstrɔːberi/" },
      { t: "Watermelon", e: "🍉", p: "/ˈwɔːtərmelən/" },
      { t: "Pineapple", e: "🍍", p: "/ˈpaɪnæpəl/" },
      { t: "Vegetable", e: "🥕", p: "/ˈvedʒtəbəl/" },
      { t: "Breakfast", e: "🍳", p: "/ˈbrekfəst/" },
      { t: "Dinner", e: "🍽️", p: "/ˈdɪnər/" },
    ],
  },
  sport: {
    color: "#00D2D3",
    label: "Sport",
    items: [
      { t: "Basketball", e: "🏀", p: "/ˈbæskɪtbɔːl/" },
      { t: "Football", e: "⚽", p: "/ˈfʊtbɔːl/" },
      { t: "Tennis", e: "🎾", p: "/ˈtenɪs/" },
      { t: "Swimming", e: "🏊", p: "/ˈswɪmɪŋ/" },
      { t: "Cycling", e: "🚴", p: "/ˈsaɪklɪŋ/" },
      { t: "Skating", e: "⛸️", p: "/ˈskeɪtɪŋ/" },
      { t: "Skiing", e: "⛷️", p: "/ˈskiːɪŋ/" },
      { t: "Surfing", e: "🏄", p: "/ˈsɜːrfɪŋ/" },
      { t: "Climbing", e: "🧗", p: "/ˈklaɪmɪŋ/" },
      { t: "Diving", e: "🤿", p: "/ˈdaɪvɪŋ/" },
    ],
  },
};
